package-lock.json
package.json
src/App.tsx
src/index.css
src/layouts/index.tsx
src/pages/home.tsx
src/pages/login.tsx
src/pages/myPage.tsx
src/pages/notice.tsx
src/pages/payment.tsx
src/routes/index.tsx

#3 
- 레이아웃 간략히 잡아두었음
- 폴더 구조 잡기
- 라우터 세팅
N/A

[Setting/#3] 폴더 구조 및 라우터 세팅

---

package-lock.json
package.json
src/assets/icons/close.svg
src/assets/icons/modalBar.svg
src/components/common/modal.tsx
src/components/modal/exampleModal.tsx
src/index.css
src/layouts/index.tsx
src/pages/home.tsx
src/stores/modalStore.ts

#6 
- 핸드폰 테스트를 위한 host 추가
- zustand 설치
- 아이콘 svg 추가
- 모달 컴포넌트 구현
- 간단한 예제 구현
- 모달 컬러값 추가
- 모달 추가로 인한 레이아웃 수정
N/A
- 예제 참고하셔서 사용하시면 될 것 같습니다 ~

[Feat/#6] Modal 컴포넌트 구현

---

src/components/coupon/CouponCard.tsx
src/constants/coupon/coupons.ts
src/pages/coupon.tsx
src/routes/index.tsx
src/stores/couponStore.ts

#59 
- 쿠폰 컴포넌트 제작
- 페이지 UI 구현
- 쿠폰 클릭 시 테두리 표시 후(2초 후) 이전 화면으로 이동

[Feat/#59] 쿠폰 페이지 구현

---

src/components/pointCard.tsx
src/constants/myPage/mainFunctions.ts
src/mocks/pointData.ts
src/pages/mypage/points.tsx
src/routes/index.tsx
src/types/point.ts

#54 
- 포인트 컴포넌트 구현
- 포인트 더미 데이터 생성
- 포인트 페이지 UI 구현
- 라우트 연결 및 추가
N/A
보유 포인트나 디테일한 데이터 불러오는 내용은 api 연결 하면서 수정할 예정입니당

[Feat/#54] 포인트 페이지 UI 구현

---

src/components/coupon/CouponCard.tsx
src/constants/myPage/mainFunctions.ts
src/pages/mypage/coupons.tsx
src/routes/index.tsx

#63 
- 쿠폰 컴포넌트 옵션 수정
- 쿠폰 컴포넌트 UI 수정
- 마이페이지 내 쿠폰 페이지 구현
- 라우트 수정
N/A
결제 페이지 내 쿠폰 페이지와 마이페이지 내 쿠폰 페이지가 다른 부분이 있어서 그 부분 다듬었습니다~!
선택, 클릭 기능을 옵션으로 바꾸고 마이페이지 내 쿠폰 페이지는 정적으로 구현하였습니당 
쿠폰 컴포넌트 UI가 손 볼 부분이 꽤 있었어서, 구현할 때&리뷰할 때 조금만 더 꼼꼼히 봐주세요!🙇‍♀️

[Feat/#63] 쿠폰 페이지 UI 구현

---

src/assets/myPage/review/close.svg
src/assets/myPage/review/plus.svg
src/assets/myPage/review/starLine.svg
src/components/review/imageUploader.tsx
src/components/review/orderItem.tsx
src/components/review/orderReviewList.tsx
src/components/review/reviewStarRating.tsx
src/mocks/orderData.ts
src/pages/mypage/writeReview.tsx
src/routes/index.tsx

#56 
- 별점 평가 구현
- 텍스트 박스 크기 고정, 글자수세기 제한 구현
- 이미지 추가 및 삭제, 장수 제한 구현
- 등록 버튼 disabled 조건 구현
- 리뷰 작성 버튼에서 useParams로 연결 구현
N/A
- 이미지 첨부하고 화면에 띄우는 부분은 제가 무지해서 AI의 도움을 받아서 수정하는 식으로 했는데.. (imageUploader.tsx) 읽어보고 과한 부분이 있다(?), 쓸모없는 코드가 없다 하시면 말씀해주세용..
- 이미지 삭제 버튼이 첨부한 이미지 끝에 매달려 있어서 이미지 크기대로 잘리는 바람에 구현이 까다로웠는데 마진이랑 패딩을 이리저리 조작해서 눈속임으로 만들어냈습니당,,😅
- onChange를 사용하는 핸들들은 추후에 api 연결 시 사용하기 위해 만들어둔 것입니다!

[Feat/#56] 리뷰 작성 페이지 UI 구현

---

src/components/common/InputField.tsx
src/pages/addAddress.tsx
src/pages/shoppingCart.tsx
src/routes/index.tsx

#69 
* 입력창 컴포넌트 사용해서 이름, 번호, 배송지 등 입력하는 화면 구현
* 전화번호, 공동 현관 비번에 정규표현식 추가
* 전화번호는 하이픈 입력 가능하도록 수정
* 공동 현관 비번은 *, # 입력 가능하도록 수정
* 기존 PR feat/69는 히스토리 중복 문제로 인해 이 PR로 대체합니다 !
* 기존 feat/69 브랜치에서 rebase 과정 중 히스토리 충돌로 인해 새로운 브랜치인 해당 브랜치로 재작업해서 실제 작업 내용만 포함했습니다 ! 😓 (이미 dev에 머지된 커밋들이 중복으로 포함되는 문제를 해결)

[Feat/#69] 배송지 추가 화면 구현

---

.github/workflows/main.yaml
vercel.json

setting: 배포 환경 세팅

---

src/pages/mypage/myPage.tsx

#107 
img 크기가 깨져 보여서 고정했습니다
N/A

fix: 프로필 이미지 크기 고정

---

src/apis/product/product.ts
src/components/product/reviewCard.tsx
src/constants/querykeys/queryKeys.ts
src/hooks/product/useGetProductDetail.ts
src/pages/product.tsx
src/pages/review.tsx
src/types/product/product.ts
src/utils/time.ts

#116 
- product 상세 api 연결
- 아직 api 수정 중이라 해당 부분 제외하고 연결하였음

[Feat] product 상세 api 연결

---

src/apis/product/option.ts
src/components/modal/dropDown.tsx
src/components/modal/optionModal.tsx
src/components/modal/shoppingCartModal.tsx
src/constants/querykeys/queryKeys.ts
src/hooks/product/useGetOption.ts
src/types/product/option.ts

#120 
- dropdown의 option list를 조회하는 api 연결

[Feat] option list api 연결

---

src/apis/auth/auth.ts
src/apis/axiosInstance.ts
src/hooks/auth/useLogout.ts
src/hooks/myPage/usePatchUserInfo.ts
src/pages/mypage/myPage.tsx

#125 
- auth api 작성(auth.ts)
- axiosInstance 토큰 인식 안정적으로 수정
- useLogout 훅 작성
- 마이 페이지에서 로그아웃 버튼 기능 활성화
- usePatchUserInfo 안 쓰는 데이터 값 삭제
N/A

[Feat/#125] 로그아웃 api 연동

---

src/apis/review/review.ts
src/components/product/reviewCard.tsx
src/constants/querykeys/queryKeys.ts
src/hooks/review/useGetInfinite.ts
src/hooks/review/useGetReviewDetail.ts
src/pages/review.tsx
src/types/product/product.ts
src/types/review/review.ts

#122 
- 리뷰 상세 하단 api 연결
- 무한 스크롤 구현
- 리뷰 상세 상단 api 연결

[Feat] 리뷰 상세 조회 api 구현

---

src/apis/product/makeTeam.ts
src/components/modal/dropDown.tsx
src/components/modal/optionModal.tsx
src/hooks/product/useMakeTeam.ts
src/pages/ApplyReturnOrExchange.tsx
src/pages/product.tsx
src/types/product/makeTeam.ts

#135 
- 팀 생성 api 연결
- 팀 생성 관련 답변 받으면 수정 예정

[Feat] 팀 생성 api 연결

---

src/apis/product/joinTeam.ts
src/apis/product/makeTeam.ts
src/hooks/product/useGetProductDetail.ts
src/hooks/product/useJoinTeam.ts
src/hooks/product/useMakeTeam.ts
src/pages/product.tsx
src/types/product/joinTeam.ts

#137 
- 팀 생성 시 invalidate 추가
- 팀 참여 api 연결

[Feat] 팀 참여 api 연결

---

src/apis/points/getPoints.ts
src/components/pointCard.tsx
src/constants/querykeys/queryKeys.ts
src/hooks/points/useInfinitePoints.ts
src/pages/mypage/points.tsx
src/types/points/TGetPoints.ts

#124 
- /api/points/history api 연동
- 관련 타입, axiosInstance, 훅, queryKey 작성
- 데이터에 맞춰 페이지 및 컴포넌트에 연결 작업

[Feat/#124] 포인트 api 연동

---

src/components/review/orderItem.tsx
src/components/review/reviewItem.tsx
src/pages/mypage/writeReview.tsx
src/types/board/reviewBoard.ts
src/types/product/product.ts
src/types/review/myReview.ts
src/types/review/review.ts

[Fix/#155] 리뷰 페이지 api 수정

---

src/components/review/imageUploader.tsx
src/components/review/orderItem.tsx
src/components/review/orderReviewList.tsx
src/pages/mypage/myReview.tsx
src/pages/mypage/writeReview.tsx
src/stores/reviewImageStore.ts

#155 
- 리뷰 쓰기 UI 수정(디자인 QA 반영)
- 리뷰 작성 페이지로 데이터 전달 코드 수정(Store 파일 생성)
- imageUploader 코드 수정(무한루프 방지)
N/A

[Fix/#155] 리뷰 페이지 api 수정-2

---

src/apis/axiosInstance.ts
src/apis/coupon/getCoupons.ts
src/hooks/coupon/useCoupons.ts
src/hooks/coupon/useInfiniteCoupons.ts
src/pages/coupon.tsx
src/pages/payment.tsx
src/types/coupon/TGetCoupons.ts
vite.config.ts

#159 
- /payment에서 선택된 쿠폰 활용
- /coupon 페이지 주석 제거 및 api 연동

[Feat/#159] 결제 페이지 쿠폰 선택 API 연동

---

src/apis/search/search.ts
src/constants/querykeys/queryKeys.ts
src/hooks/category/useCategoryProduct.ts
src/hooks/search/useKeywordProduct.ts
src/pages/search.tsx
src/types/category.ts
src/types/search/search.ts

[refactor/#146] refactor: category keyword

---

src/components/search/tag.tsx
src/hooks/customQuery.ts
src/hooks/search/useDeleteRecent.ts
src/hooks/search/useKeywordProduct.ts
src/pages/search.tsx

#145 
- Tag 삭제시 UI 업데이트 안되던 문제 해결
- 상품 검색 api 연결

[Feat] 상품 검색 api 연결

---

src/apis/auth/auth.ts
src/apis/axiosInstance.ts
src/apis/members/members.ts
src/apis/search/recent.ts
src/components/common/SearchInput.tsx
src/components/common/modal.tsx
src/components/home/banner.tsx
src/components/modal/optionModal.tsx
src/components/product/reviewCard.tsx
src/components/search/tag.tsx
src/context/AuthContext.tsx
src/hooks/category/useCategoryProduct.ts
src/hooks/home/useGetProduct.ts
src/hooks/product/useGetProductDetail.ts
src/hooks/search/useGetRecent.ts
src/hooks/search/useKeywordProduct.ts
src/layouts/ProtectedLayout.tsx
src/pages/home.tsx
src/pages/onBoarding.tsx
src/pages/product.tsx
src/pages/search.tsx
src/routes/index.tsx
src/types/category.ts
src/types/search/search.ts
src/utils/storage.ts

#173 
- 생각보다 많은 걸 고쳐버렸습니다
- 회원 비회원 분기 처리가 필요한데 임시로 optionalAuth 사용
- 모달 두개 슬라이드 효과 적용
- 배너 자동 슬라이드 모듈 추가
- 옵션 선택 없는 경우 버튼 비활성화
- 리뷰 이미지 크기 재조정
- tag delete 부분이 작아서 padding 조정
- 정렬 오류 -> 타입 오류여서 수정
- 온보딩에서 업종 저장하던 부분 -> 홈으로 수정
- 홈에서 여러번 업종 저장 -> 최초 1회만 저장
- 수정 반영하면서 auth부분 다시 돌려놓을 예정 ~~

[Refactor] 회원 비회원 분기 처리

---

src/apis/address/address.ts
src/apis/coupon/getCoupons.ts
src/components/coupon/CouponCard.tsx
src/components/head_bottom/ProductHeader.tsx
src/constants/querykeys/queryKeys.ts
src/hooks/address/useAddress.ts
src/hooks/coupon/useCoupons.ts
src/hooks/coupon/useInfiniteCoupons.ts
src/pages/addressChange.tsx
src/pages/coupon.tsx
src/pages/payment.tsx
src/pages/shoppingCart.tsx
src/types/address/TAddress.ts
src/types/cart/TCart.ts
src/types/coupon/TGetCoupons.ts

#175 
- /mypage/coupon과 동일하게 /coupon 페이지의 쿠폰 조회도 무한스크롤로 변경
- /mypage/coupon의 무한 호출 이슈 해결
- N/A
테스트 시 쿠폰 id 2~4는 오류 뜨는게 맞습니다!
- 4- COUPON4007
- 3- COUPON4003
- 2- COUPON4006

[Refactor/#175] 쿠폰 무한 스크롤 적용 및 적용/수정 기능 리팩토링

---

src/apis/auth/auth.ts
src/apis/axiosInstance.ts
src/apis/members/members.ts
src/apis/search/recent.ts
src/context/AuthContext.tsx
src/hooks/search/useGetRecent.ts
src/layouts/ProtectedLayout.tsx
src/pages/search.tsx
src/routes/index.tsx

#183 
- auth 코드 되돌렷음
- api 수정 반영

[Refactor] search 부분 api 수정 반영

---

src/apis/auth/auth.ts
src/hooks/myPage/useUserInfo.ts
src/layouts/ProtectedLayout.tsx

#187 
me와 reissue 한 번만 호출되도록 수정
me 옵션 변경
N/A

[Bug/#187] /me 무한 재호출 버그 수정

---

src/components/common/SearchInput.tsx
src/components/modal/homeModal.tsx
src/pages/search.tsx

#191 
- 포인트 페이지 라우트 연결
- 키보드 확대 튐 해결
- 키보드 내려가게 설정

[Fix] 홈, 검색창 피드백 반영

---

src/layouts/index.tsx

[Fix/#199] 바텀바-버튼 동시 렌더링 이슈 해결

---

src/apis/notifications/notifications.ts
src/components/Subscriber.tsx
src/components/common/modal.tsx
src/components/head_bottom/HomeHeader.tsx
src/components/modal/TeamModal.tsx
src/components/notiCard.tsx
src/hooks/notifications/useGetNotiUnread.ts
src/layouts/index.tsx
src/stores/modalStore.ts
src/types/notifications/TGetNotiList.ts

#162 
- Subscriber 컴포넌트 제작(api 연동)
- 팀매칭 모달 TeamModal 연결
- 알림 목록에서 온클릭 기능 추가
- 알림 타입 detail 필드 추가
- 모달 컴포넌트 타입 안 담김 버그 수정
- 홈헤더에 안읽은 알림 개수 기능 추가 구현
N/A

[Feat/#162] 실시간 구독 api 연동

---

src/components/modal/optionModal.tsx

[Fix] svg 사이즈 변경

---

src/hooks/home/useGetProduct.ts
src/hooks/search/useKeywordProduct.ts
src/pages/home.tsx
src/pages/search.tsx
src/types/search/search.ts

#216 
- 검색 결과 무한 스크롤 적용
- 로딩 스피너 추가

[Refactor] 검색 결과 무한 스크롤 적용

---

src/pages/agreement.tsx

fix: 페이지 리사이징 수정

---

src/components/modal/optionModal.tsx
src/components/review/orderItem.tsx
src/hooks/team/useTeamJoinCart.ts
src/pages/addressChange.tsx
src/pages/feedback/paymentStatus.tsx
src/pages/payment.tsx
src/pages/shoppingCart.tsx

[Refactor/#230] 피드백 반영

---

src/hooks/payment/useTossPayments.ts

[Add/#230] 환경 변수 테스트

---

src/pages/agreement.tsx
src/pages/home.tsx
src/utils/storage.ts

#241 
- 회원가입시 업종을 저장하는 방식으로 변경

[Fix] 회원가입시 업종 저장

---

src/hooks/members/usePostAgree.ts
src/pages/agreement.tsx

[Fix] 회원가입 성공시 업종 저장

---

package-lock.json
package.json
src/components/coupon/CouponCard.tsx
src/components/modal/optionModal.tsx
src/components/review/orderItem.tsx
src/hooks/coupon/useCoupons.ts
src/hooks/payment/usePaymentConfirm.ts
src/hooks/payment/usePaymentStatus.ts
src/hooks/product/useJoinTeam.ts
src/pages/ApplyReturnOrExchange.tsx
src/pages/coupon.tsx
src/pages/feedback/PaymentStatusHandler.tsx
src/pages/feedback/paymentStatus.tsx
src/pages/feedback/paymentStatusWrapper.tsx
src/pages/mypage/coupons.tsx
src/pages/payment.tsx
src/types/cart/TCart.ts
src/types/coupon/TGetCoupons.ts

#248 
- 쿠폰 정렬 기준을 사용 가능(할인가 높은 순) → 조건 미충족 → 사용 불가 순으로 수정
- CouponCard 컴포넌트에 위 3가지 상태에 따라 비활성화 표시하도록 수정
- 즉시 결제(바로 구매)에서 결제 완료 후, 해당 상품이 장바구니에서 자동으로 삭제되도록 수정
- clsx 설치 했습니다 ! (npm install clsx)

[Fix/#248] 쿠폰 페이지 / 결제 플로우에서 발생하는 버그 수정

---

src/pages/photoReview.tsx
src/pages/review.tsx

[Fix] 정렬 오류 수정

---

src/components/head_bottom/HomeHeader.tsx
src/layouts/ProtectedLayout.tsx
src/pages/mypage/profile.tsx

#270 
- 프로필수정 전화번호 없어도 저장 가능
- alert를 toast로 변경
- 알림 뱃지 위치 조정
- 9+를 +로 변경
- subscriber protectedLayout에서 삭제
N/A

[Fix/#270] 요청사항 반영
